version: '2'
services:
  web:
    build: .
    container_name: spot-web
    ports:
     - "6000:6000"
    volumes:
      - .:/var/www/html
    ports:
      - 8088:80
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql
    container_name: spot-db
    environment:
      - MYSQL_ROOT_PASSWORD=oshry81
    ports:
      - "3388:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: spot-phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=oshry81
    links:
      - db:mysql_db_server
    ports:
      - "8099:80"
